name: release-please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: MkDocsYamlSchemaPlugin
          default-branch: main
        
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0

      - name: Set up Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          python setup.py sdist
      - name: Publish to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
